### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by hvze** [grz0zrg/fbg#1]
Just FYI: `parrallel` is just `parallel` :)

**Comment by grz0zrg** [comment]
Fixed. Thank you! (there are some other typo errors as well, will check it later on)

**Comment by tay10r** [comment]
@grz0zrg It's better to leave issues open until they're resolved.

**Comment by Vorlent** [comment]
Unfortunately there are still some spelling issues. The description of the github site still has the old spelling.

> FBGraphics (FBG) is a simple C 24 bpp graphics library for the Linux framebuffer with **parralelism** support.

The edit button is in the top right corner and only the owner of the repository can change the description I believe.
