### ISSUE TITLE
STB_Image?

### ISSUE THREAD

**Issue by RobLoach** [grz0zrg/fbg#16]
[stb_image.h](https://github.com/nothings/stb/blob/master/stb_image.h) from the [stb headers](https://github.com/nothings/stb/) seems to support more formats in a standardized API. May ease up the dependency tree from lodepng and nanojpg. Could be a good addition along-side the other loaders.

**Comment by grz0zrg** [comment]
Thank you. I don't know much the differences between the libraries but as far as i can tell stb_image may replace lodepng and nanojpg in the future.
