### ISSUE TITLE
running on 32bpp machine segfaults

### ISSUE THREAD

**Issue by donbright** [grz0zrg/fbg#5]
Hello,

I got it built (had to tweak Makefile to remove link to blahblah711 library). I ran this on a machine in 32bpp mode and it segfaulted. I know it's only supposed to run 24bpp but segfaults can be a security issue IIRC. Thanks. 

```
don@oysters:/tmp/fbg/examples$ ./quickstart 
fbg_init: Cannot open '/dev/fb0'!
Segmentation fault (core dumped)
don@oysters:/tmp/fbg/examples$ sudo ./quickstart 
[sudo] password for don: 
fbg_init: '/dev/fb0' (1366x768 (1366x768 virtual) 32 bpp (8/16, 8/8, 8/0) (4227072 smen_len) 5504 line_length)
fbg_init: '/dev/fb0' Unsupported format (only 24 bits framebuffer is supported)!
Segmentation fault

```

**Comment by grz0zrg** [comment]
Indeed, this happen because there is no checks in the examples for when the library fail to initialize, i will see to check the library initialization on all examples.

**Comment by grz0zrg** [comment]
Fixed in last commit.
