### ISSUE TITLE
Create custom renderer

### ISSUE THREAD

**Issue by TheGreatRambler** [grz0zrg/fbg#8]
I am dealing with a swizzled framebuffer I allocate in Nintendo Switch homebrew. I don't have the memory to be able to create a context in fbg and then render to the swizzled framebuffer, so is it possible to create my own renderer class that defines a function for setting a pixel? Thank you

**Comment by grz0zrg** [comment]
This is actually tricky and not possible right now because fbg manipulate its own internal buffers so it always allocate some buffers even with a custom backend upon a call to `fbg_customSetup`.

I may see if i can provide a solution later on, this is kinda interesting especially for embedded low memory hardware.

**Comment by TheGreatRambler** [comment]
I've been looking for some simple software rendered drawing routines for scripting purposes. I don't need a UI.

**Comment by TheGreatRambler** [comment]
As an aside, would it be possible to host the documentation on a github page?

**Comment by grz0zrg** [comment]
Pushed some features which may provide a solution for low memory embedded hardware. Moved the fbdev framebuffer code into a specific backend and allowed to bypass buffers initialization.

Wrote a small GBA backend showing how a low memory footprint backend can be created : 

https://github.com/grz0zrg/fbg/blob/master/custom_backend/gba/fbg_gba.c

Basically to create a rendering backend you only need to work around the `fbg_customSetup` function which now has an argument to bypass internal buffers initialization, you may then initialize the `fbg->back_buffer` yourself (this is where all fbg calls will draw) either by allocating it (like the GBA example does) and doing conversion in your custom backend fbg_draw function if your final buffer has an unusual format or you could assign an already allocated buffer but it must be 24 / 32 bpp.

**Comment by TheGreatRambler** [comment]
This is fantastic, I like the passing of a custom context, I can pass my cpp class. Thank you!
